[package]
name = "kademlia_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
sha2 = "0.10.8"
tokio = "1.35.1"
